import{initializeApp}from"https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js";
import{getAuth,signInAnonymously}from"https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js";
import{getFirestore,collection,query,orderBy,limit,onSnapshot,addDoc,serverTimestamp}from"https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js";
import{firebaseConfig}from"./firebase-config.js?v=20261009h";
const repo="tmfvnsgkfn-tech/cheonsal",$=id=>document.getElementById(id),grid=$("galleryGrid"),status=$("galleryStatus"),ext=/\.(jpg|jpeg|png|webp|gif)$/i;
let db=null,auth=null,authReady=Promise.resolve(false);
try{const app=initializeApp(firebaseConfig);auth=getAuth(app);db=getFirestore(app);authReady=signInAnonymously(auth).then(()=>true).catch(e=>{console.warn("Anonymous login failed",e);return false})}catch(e){console.warn("Gallery comments auth:",e)}
const safeTitle=name=>name.replace(ext,"").replace(/[_-]/g," ");
async function addComments(article,file){const block=document.createElement("section");block.className="gallery-comments";const head=document.createElement("strong");head.textContent="💬 익명 댓글";const list=document.createElement("div");list.className="gallery-comment-list";list.textContent="댓글 불러오는 중…";const form=document.createElement("form");form.className="gallery-comment-form";const input=document.createElement("input");input.maxLength=300;input.required=true;input.placeholder="익명으로 댓글을 남겨보세요 (300자 이내)";input.setAttribute("aria-label","익명 댓글");const button=document.createElement("button");button.type="submit";button.textContent="등록";const msg=document.createElement("small");msg.className="gallery-comment-msg";form.append(input,button);block.append(head,list,form,msg);article.append(block);
list.textContent="댓글 연결 중…";button.disabled=true;const ready=await authReady;if(!db||!ready||!auth?.currentUser){list.textContent="댓글 로그인 연결 실패. 새로고침 후 다시 시도해 주세요.";return}button.disabled=false;
const photoId=encodeURIComponent(file.name),comments=collection(db,"cheonsal_gallery_comments",photoId,"comments");let last=0;
onSnapshot(query(comments,orderBy("createdAt","asc"),limit(100)),snap=>{list.replaceChildren();if(snap.empty){list.textContent="아직 댓글이 없습니다. 첫 댓글을 남겨보세요!";return}snap.forEach(d=>{const data=d.data();const p=document.createElement("p");const who=document.createElement("b");who.textContent="익명";const date=document.createElement("small");date.textContent=" · "+(data.createdAt?.toDate?.()?.toLocaleString("ko-KR")||"방금");const text=document.createElement("span");text.textContent=data.body;p.append(who,date,document.createElement("br"),text);list.append(p)})},e=>{list.textContent="댓글을 불러올 수 없습니다. Firebase 보안 규칙을 확인해 주세요.";console.warn(e)});
form.addEventListener("submit",async e=>{e.preventDefault();if(Date.now()-last<10000){msg.textContent="댓글은 10초 간격으로 작성할 수 있어요.";return}const body=input.value.trim();if(!body)return;button.disabled=true;msg.textContent="등록 중…";try{await addDoc(comments,{body,uid:auth.currentUser.uid,createdAt:serverTimestamp()});last=Date.now();input.value="";msg.textContent="댓글 등록 완료"}catch(err){msg.textContent="댓글 등록 실패: Firebase 규칙 설정을 확인해 주세요.";console.error(err)}finally{button.disabled=false}})}

const attached=new WeakSet();function attach(){for(const article of document.querySelectorAll(".gallery-card")){if(attached.has(article))continue;attached.add(article);const img=article.querySelector("img");const file={name:img?.alt||""};addComments(article,file)}}new MutationObserver(attach).observe(grid,{childList:true});attach();
