import{initializeApp}from"https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js";
import{getAuth,signInAnonymously}from"https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js";
import{getFirestore,collection,query,orderBy,limit,onSnapshot,addDoc,serverTimestamp}from"https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js";
import{firebaseConfig}from"./firebase-config.js?v=20261009h";
const repo="tmfvnsgkfn-tech/cheonsal",$=id=>document.getElementById(id),grid=$("galleryGrid"),status=$("galleryStatus"),ext=/\.(jpg|jpeg|png|webp|gif)$/i;
let db=null,auth=null;
try{const app=initializeApp(firebaseConfig);auth=getAuth(app);db=getFirestore(app);await signInAnonymously(auth)}catch(e){console.warn("Gallery comments auth:",e)}
const safeTitle=name=>name.replace(ext,"").replace(/[_-]/g," ");
function addComments(article,file){const block=document.createElement("section");block.className="gallery-comments";const head=document.createElement("strong");head.textContent="💬 익명 댓글";const list=document.createElement("div");list.className="gallery-comment-list";list.textContent="댓글 불러오는 중…";const form=document.createElement("form");form.className="gallery-comment-form";const input=document.createElement("input");input.maxLength=300;input.required=true;input.placeholder="익명으로 댓글을 남겨보세요 (300자 이내)";input.setAttribute("aria-label","익명 댓글");const button=document.createElement("button");button.type="submit";button.textContent="등록";const msg=document.createElement("small");msg.className="gallery-comment-msg";form.append(input,button);block.append(head,list,form,msg);article.append(block);
if(!db||!auth?.currentUser){list.textContent="댓글 서비스에 연결할 수 없습니다.";button.disabled=true;return}
const photoId=encodeURIComponent(file.name),comments=collection(db,"cheonsal_gallery_comments",photoId,"comments");let last=0;
onSnapshot(query(comments,orderBy("createdAt","asc"),limit(100)),snap=>{list.replaceChildren();if(snap.empty){list.textContent="아직 댓글이 없습니다. 첫 댓글을 남겨보세요!";return}snap.forEach(d=>{const data=d.data();const p=document.createElement("p");const who=document.createElement("b");who.textContent="익명";const date=document.createElement("small");date.textContent=" · "+(data.createdAt?.toDate?.()?.toLocaleString("ko-KR")||"방금");const text=document.createElement("span");text.textContent=data.body;p.append(who,date,document.createElement("br"),text);list.append(p)})},e=>{list.textContent="댓글을 불러올 수 없습니다. Firebase 보안 규칙을 확인해 주세요.";console.warn(e)});
form.addEventListener("submit",async e=>{e.preventDefault();if(Date.now()-last<10000){msg.textContent="댓글은 10초 간격으로 작성할 수 있어요.";return}const body=input.value.trim();if(!body)return;button.disabled=true;msg.textContent="등록 중…";try{await addDoc(comments,{body,uid:auth.currentUser.uid,createdAt:serverTimestamp()});last=Date.now();input.value="";msg.textContent="댓글 등록 완료"}catch(err){msg.textContent="댓글 등록 실패: Firebase 규칙 설정을 확인해 주세요.";console.error(err)}finally{button.disabled=false}})}
fetch("https://api.github.com/repos/"+repo+"/contents/gallery-photos?ts="+Date.now(),{cache:"no-store",headers:{Accept:"application/vnd.github+json"}}).then(async r=>{if(!r.ok)throw Error("사진 목록 오류 ("+r.status+")");return r.json()}).then(files=>{const images=files.filter(f=>f.type==="file"&&ext.test(f.name)).reverse();status.textContent="천살의 추억 "+images.length+"장";grid.replaceChildren();if(!images.length){grid.innerHTML='<div class="gallery-empty">아직 등록된 사진이 없습니다.<p>첫 번째 천살 추억을 기다리고 있어요! 📸</p></div>';return}for(const f of images){const article=document.createElement("article");article.className="gallery-card";const img=document.createElement("img");img.src="gallery-photos/"+encodeURIComponent(f.name);img.onerror=()=>{if(!img.dataset.fallback){img.dataset.fallback="1";img.src=f.download_url||"https://raw.githubusercontent.com/"+repo+"/main/gallery-photos/"+encodeURIComponent(f.name)}};img.alt=safeTitle(f.name);img.loading="lazy";img.addEventListener("click",()=>{$("galleryLarge").src=img.src;$("galleryDialog").showModal()});const caption=document.createElement("div");caption.className="gallery-caption";const title=document.createElement("strong");title.textContent=safeTitle(f.name);caption.append(title);article.append(img,caption);addComments(article,f);grid.append(article)}}).catch(e=>{status.textContent="사진을 불러오지 못했습니다.";grid.innerHTML='<div class="gallery-empty">잠시 후 새로고침해 주세요.</div>';console.error(e)});
$("galleryDialogClose").addEventListener("click",()=>$("galleryDialog").close());
