import{initializeApp}from"https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js";
import{getAuth,onAuthStateChanged,signInWithEmailAndPassword,signOut}from"https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js";
import{getFirestore,collection,query,orderBy,limit,onSnapshot,addDoc,deleteDoc,doc,serverTimestamp}from"https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js";
import{getStorage,ref,uploadBytes,getDownloadURL,deleteObject}from"https://www.gstatic.com/firebasejs/10.14.1/firebase-storage.js";
import{firebaseConfig}from"./firebase-config.js?v=20261009h";
const $=id=>document.getElementById(id),esc=s=>{const e=document.createElement("span");e.textContent=String(s??"");return e.innerHTML};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),storage=getStorage(app);
const collectionRef=collection(db,"cheonsal_gallery");
const ADMIN_UID="REPLACE_WITH_ADMIN_UID";
let currentUser=null,photos=[],selected="전체";
const adminStatus=$("galleryAdminStatus"),grid=$("galleryGrid");
function isAdmin(){return currentUser?.uid===ADMIN_UID&&ADMIN_UID!=="REPLACE_WITH_ADMIN_UID"}
function showAdmin(){const ok=isAdmin();$("adminLoggedIn").hidden=!ok;$("adminLoggedOut").hidden=ok;grid.querySelectorAll(".gallery-delete").forEach(b=>b.hidden=!ok)}
function render(){grid.replaceChildren();const visible=photos.filter(p=>selected==="전체"||p.category===selected);if(!visible.length){grid.innerHTML='<div class="gallery-empty">아직 이 카테고리에 등록된 사진이 없습니다.<p>천살의 첫 추억을 기다리고 있어요! 📸</p></div>';return}for(const p of visible){const article=document.createElement("article");article.className="gallery-card";const img=document.createElement("img");img.src=p.url;img.alt=p.title||"천살 추억";img.loading="lazy";img.addEventListener("click",()=>{$("galleryLarge").src=p.url;$("galleryDialog").showModal()});const caption=document.createElement("div");caption.className="gallery-caption";caption.innerHTML="<strong>"+esc(p.title)+"</strong><small>"+esc(p.category)+" · "+esc(p.createdAt?.toDate?.()?.toLocaleDateString("ko-KR")||"최근")+"</small>"+(p.description?"<p>"+esc(p.description)+"</p>":"");const del=document.createElement("button");del.className="gallery-delete";del.textContent="사진 삭제";del.hidden=!isAdmin();del.addEventListener("click",async()=>{if(!isAdmin()||!confirm("이 사진을 삭제할까요?"))return;try{await deleteDoc(doc(db,"cheonsal_gallery",p.id));if(p.path)await deleteObject(ref(storage,p.path));adminStatus.textContent="사진 삭제 완료"}catch(e){adminStatus.textContent="삭제 실패: "+(e.code||e.message)}});article.append(img,caption,del);grid.append(article)}}
document.querySelectorAll("#galleryFilters button").forEach(b=>b.addEventListener("click",()=>{selected=b.dataset.category;document.querySelectorAll("#galleryFilters button").forEach(x=>x.classList.toggle("active",x===b));render()}));
onSnapshot(query(collectionRef,orderBy("createdAt","desc"),limit(100)),snap=>{photos=snap.docs.map(d=>({id:d.id,...d.data()}));$("galleryStatus").textContent="천살의 추억 "+photos.length+"장";render()},e=>{$("galleryStatus").textContent="사진 조회 실패: "+(e.code||e.message)});
onAuthStateChanged(auth,user=>{currentUser=user;showAdmin();if(user&&!isAdmin()){adminStatus.textContent="관리자 권한이 없는 계정입니다. 로그인은 가능해도 사진을 올릴 수 없습니다."}});
$("galleryLogin").addEventListener("submit",async e=>{e.preventDefault();adminStatus.textContent="로그인 중…";try{await signInWithEmailAndPassword(auth,$("galleryEmail").value.trim(),$("galleryPassword").value);adminStatus.textContent=isAdmin()?"관리자 로그인 성공":"로그인은 되었지만 관리자 UID가 등록되지 않았습니다.";$("galleryPassword").value=""}catch(err){adminStatus.textContent="로그인 실패: "+(err.code||err.message)}});
$("galleryLogout").addEventListener("click",async()=>{await signOut(auth);adminStatus.textContent="로그아웃했습니다."});
$("galleryFile").addEventListener("change",()=>{const f=$("galleryFile").files[0],img=$("galleryPreview");if(!f){img.style.display="none";return}img.src=URL.createObjectURL(f);img.style.display="block"});
$("galleryUpload").addEventListener("submit",async e=>{e.preventDefault();if(!isAdmin()){adminStatus.textContent="관리자 권한이 필요합니다.";return}const file=$("galleryFile").files[0];if(!file||!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>10*1024*1024){adminStatus.textContent="JPG, PNG, WEBP 형식의 10MB 이하 사진만 가능합니다.";return}const btn=$("galleryUploadButton");btn.disabled=true;adminStatus.textContent="사진 업로드 중…";const path="cheonsal_gallery/"+auth.currentUser.uid+"/"+Date.now()+"-"+Math.random().toString(36).slice(2)+"."+({ "image/jpeg":"jpg","image/png":"png","image/webp":"webp"}[file.type]);try{const imageRef=ref(storage,path);await uploadBytes(imageRef,file,{contentType:file.type});const url=await getDownloadURL(imageRef);try{await addDoc(collectionRef,{title:$("galleryTitle").value.trim(),category:$("galleryCategory").value,description:$("galleryDescription").value.trim(),url,path,createdAt:serverTimestamp(),uid:auth.currentUser.uid})}catch(e){await deleteObject(imageRef).catch(()=>{});throw e}$("galleryUpload").reset();$("galleryPreview").style.display="none";adminStatus.textContent="사진 등록 완료!"}catch(err){adminStatus.textContent="등록 실패: "+(err.code||err.message)}finally{btn.disabled=false}});
$("galleryDialogClose").addEventListener("click",()=>$("galleryDialog").close());
